<?php

namespace Proxies\__CG__\Taller\RutaMicroBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Sucursal extends \Taller\RutaMicroBundle\Entity\Sucursal implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setAbreviacion($abreviacion)
    {
        $this->__load();
        return parent::setAbreviacion($abreviacion);
    }

    public function getAbreviacion()
    {
        $this->__load();
        return parent::getAbreviacion();
    }

    public function setUbicacion($ubicacion)
    {
        $this->__load();
        return parent::setUbicacion($ubicacion);
    }

    public function getUbicacion()
    {
        $this->__load();
        return parent::getUbicacion();
    }

    public function setLatitud($latitud)
    {
        $this->__load();
        return parent::setLatitud($latitud);
    }

    public function getLatitud()
    {
        $this->__load();
        return parent::getLatitud();
    }

    public function setLongitud($longitud)
    {
        $this->__load();
        return parent::setLongitud($longitud);
    }

    public function getLongitud()
    {
        $this->__load();
        return parent::getLongitud();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setEntidad(\Taller\RutaMicroBundle\Entity\Entidad $entidad = NULL)
    {
        $this->__load();
        return parent::setEntidad($entidad);
    }

    public function getEntidad()
    {
        $this->__load();
        return parent::getEntidad();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'descripcion', 'abreviacion', 'ubicacion', 'latitud', 'longitud', 'estado', 'entidad');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}