Taller\RutaMicroBundle\Entity\Caja:
    type: entity
    table: caja
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nro:
            type: integer
            unsigned: false
            nullable: false
        descripcion:
            type: string
            length: 50
            fixed: false
            nullable: false
        estado:
            type: boolean
            nullable: false
    manyToOne:
        sucursal:
            targetEntity: Sucursal
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sucursal_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
