caja:
    pattern:  /
    defaults: { _controller: "RutaMicroBundle:Caja:index" }

caja_show:
    pattern:  /{id}/show
    defaults: { _controller: "RutaMicroBundle:Caja:show" }

caja_new:
    pattern:  /new
    defaults: { _controller: "RutaMicroBundle:Caja:new" }

caja_create:
    pattern:  /create
    defaults: { _controller: "RutaMicroBundle:Caja:create" }
    requirements: { _method: post }

caja_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RutaMicroBundle:Caja:edit" }

caja_update:
    pattern:  /{id}/update
    defaults: { _controller: "RutaMicroBundle:Caja:update" }
    requirements: { _method: post|put }

caja_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RutaMicroBundle:Caja:delete" }
    requirements: { _method: post|delete }
