roles:
    pattern:  /
    defaults: { _controller: "RutaMicroBundle:Roles:index" }

roles_show:
    pattern:  /{id}/show
    defaults: { _controller: "RutaMicroBundle:Roles:show" }

roles_new:
    pattern:  /new
    defaults: { _controller: "RutaMicroBundle:Roles:new" }

roles_create:
    pattern:  /create
    defaults: { _controller: "RutaMicroBundle:Roles:create" }
    requirements: { _method: post }

roles_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RutaMicroBundle:Roles:edit" }

roles_update:
    pattern:  /{id}/update
    defaults: { _controller: "RutaMicroBundle:Roles:update" }
    requirements: { _method: post|put }

roles_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RutaMicroBundle:Roles:delete" }
    requirements: { _method: post|delete }
