ruta:
    pattern:  /
    defaults: { _controller: "RutaMicroBundle:Ruta:index" }

ruta_show:
    pattern:  /{id}/show
    defaults: { _controller: "RutaMicroBundle:Ruta:show" }

ruta_new:
    pattern:  /new
    defaults: { _controller: "RutaMicroBundle:Ruta:new" }

ruta_create:
    pattern:  /create
    defaults: { _controller: "RutaMicroBundle:Ruta:create" }
    requirements: { _method: post }

ruta_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RutaMicroBundle:Ruta:edit" }

ruta_update:
    pattern:  /{id}/update
    defaults: { _controller: "RutaMicroBundle:Ruta:update" }
    requirements: { _method: post|put }

ruta_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RutaMicroBundle:Ruta:delete" }
    requirements: { _method: post|delete }
