sucursal:
    pattern:  /
    defaults: { _controller: "RutaMicroBundle:Sucursal:index" }

sucursal_show:
    pattern:  /{id}/show
    defaults: { _controller: "RutaMicroBundle:Sucursal:show" }

sucursal_new:
    pattern:  /new
    defaults: { _controller: "RutaMicroBundle:Sucursal:new" }

sucursal_create:
    pattern:  /create
    defaults: { _controller: "RutaMicroBundle:Sucursal:create" }
    requirements: { _method: post }

sucursal_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RutaMicroBundle:Sucursal:edit" }

sucursal_update:
    pattern:  /{id}/update
    defaults: { _controller: "RutaMicroBundle:Sucursal:update" }
    requirements: { _method: post|put }

sucursal_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RutaMicroBundle:Sucursal:delete" }
    requirements: { _method: post|delete }
